### ISSUE TITLE
consider using # for black and . for no solution

### ISSUE THREAD

**Issue by martindemello** [viresh-ratnakar/exolve#1]
Alphanumeric characters like 0 are often used in rebus grids.

**Comment by viresh-ratnakar** [comment]
The .puz ascii format uses . for black and many people use it (I have some files too). Agree about 0 though. Hmm. I've already used _, |, +, @, *.

Maybe $ for no solution?

I'll also need to tweak my state-saving code if I make this change.

**Comment by martindemello** [comment]
yeah, or maybe + or ? (though ? looks a bit ugly)

**Comment by viresh-ratnakar** [comment]
Can you point to to an example rebus with 0s? Perhaps I can solve this some other way ..

**Comment by martindemello** [comment]
not offhand, but i've defnitely done american style crosswords where some of the squares were numbers (and symbols, for that matter). the hard part is you need a way to represent a partially filled in grid, so you have to pick one character to be the "unfilled square" character, and <space> is awkward to use.

**Comment by viresh-ratnakar** [comment]
OK. I think I should perhaps be able to handle them by forcing the setter to somehow "escape" the 0 in the exolve format, given that these are uncommon. But please send me an example whenever you run into one next, thanks!

**Comment by viresh-ratnakar** [comment]
Closing this. I'll deal with handling support for saving/indicating 0s as entries using some escape sequence.
