### ISSUE TITLE
Some (desktop) keyboard navigation feature requests

### ISSUE THREAD

**Issue by Antagony1060** [viresh-ratnakar/exolve#10]
1. Could it have tab and shift-tab to jump between next/previous clues, as ordered in the clue lists. They do this with the Guardian crossword and it's easily the best way to navigate their grids, I find.

2. Could the automatic jump from the end of a light to the next open square on the row, be optional? I personally find it more annoying than useful and have to navigate back to the previous light most times.

3. Last but not least: it could do with a simple keyboard method to change direction. From 1a in your [Fifteen Puzzles grid](https://viresh-ratnakar.github.io/gussalufz-12-unsolved.html) for example, getting to 1d is not straightforward without the mouse. The fewest number of key presses I could manage it in was 9! Now you might ask, *"what's wrong with using the mouse?"* Well nothing, except that filling a crossword is typing, which most people use both hands for, so having to switch to the mouse, even if infrequently, can be a distraction/annoyance. Since the 'Enter' key isn't usually used for any purpose in filling crosswords, might I suggest using that?

**Comment by viresh-ratnakar** [comment]
All excellent suggestions, thanks! I'll try to implement asap.

**Comment by Antagony1060** [comment]
That's great, thanks! 

I have to say I'm very impressed by the flexibility of the clue list formatting. I've tried out all sorts of things and most of them just worked. [One of our puzzles](https://aotw-grids.droppages.com/grids/grid006) even has a multi-line clue, which I thought would probably have to go on one line, but I stuck in some break tags anyway, more in hope than expectation, and bam! Not only did it work right away, it was properly indented to boot! Again, great job! And thank you for making it open source.

**Comment by viresh-ratnakar** [comment]
Thanks -- stuff "just working" naturally is indeed the happiest kind of working, something to always strive for!

I've checked in v0.24 which provides the navigation features requested. Please check when you get the chance.

**Comment by Antagony1060** [comment]
You know when I said that [multiline clue (2 down)](https://r-crosswords.github.io/aotw/grids/grid006.html) just worked, well I kinda lied! :\^) I hadn't noticed that selecting the clue results in the current-clue box obscuring part of the grid, including the first letter of the clue's own light. 

Any chance of a fix? I would suggest just replacing the line breaks with spaces, but you may prefer to reposition things so I'll leave that to your discretion.

**Comment by viresh-ratnakar** [comment]
Fixed in v0.28: I now replace <br> tags in clues with "/" for rendering in the "current clue" strip.

**Comment by Antagony1060** [comment]
I'm happy with that, thanks!

**Comment by viresh-ratnakar** [comment]
Ah, I should have added spaces around the "/" (will fix in the next
version). You can work around for now by putting spaces around your <br>
tags, if you like.

**Comment by Antagony1060** [comment]
No worries. I hadn't noticed that because there _is_ a space to the right of the slash and with quotation marks on the left it wasn't obvious.

I did wonder whether the pipe symbol (|) might be a better divider, as it's less likely to be used in a clue's text and, to my eyes at least, looks somewhat cleaner. But to be honest I don't think it really matters much, given how rare multiline clues are likely to be.

**Comment by viresh-ratnakar** [comment]
I like "/" because it is also commonly used for showing line breaks when
quoting poetry in prose (see, for example,
https://writingcenter.ashford.edu/slashes).

**Comment by Antagony1060** [comment]
Honestly, it's fine! :\^)

**Comment by Antagony1060** [comment]
Any chance you could make the tab navigation wrap between the last and first clues of each direction – i.e. the last across clue tabs to the first down clue, the last down clue tabs to the first across clue, and vice versa for shift tabbing?

PS. please say if you'd rather I opened a new issue rather than re-opening this one.

**Comment by viresh-ratnakar** [comment]
Done, in v0.49. ptal.

**Comment by Antagony1060** [comment]
Great job as usual, thanks!
