### ISSUE TITLE
Rebus Cells don't work with allow-digits or allow-chars

### ISSUE THREAD

**Issue by criptik** [viresh-ratnakar/exolve#108]
Test case here:
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<link rel="stylesheet" type="text/css" href="exolve-m.css?v1.58"/>
<script src="exolve-m.js?v1.58"></script>

<title>Test-Rebus</title>

</head>
<body>
    <script>
     createExolve(`
======REPLACE WITH YOUR PUZZLE BELOW======

exolve-begin
  exolve-title: Rebus test
  exolve-width: 3
  exolve-height: 3
  exolve-option: rebus-cells
  exolve-option: allow-digits
  exolve-grid:
    123 G E
    DO  . A
    M   E T
  exolve-across:
  1 Something (3)
  3 Something (3)
  exolve-down
  1 Something (3)
  2 Something (3)
exolve-end

======REPLACE WITH YOUR PUZZLE ABOVE======
     `);
    </script>
</body>
</html>

**Comment by viresh-ratnakar** [comment]
This should now be fixed, with v1.59. PTAL, thanks.

**Comment by viresh-ratnakar** [comment]
Will close this bug tomorrow (can always reopen if there is some issue).
