### ISSUE TITLE
Remove line and empty space when not required

### ISSUE THREAD

**Issue by Antagony1060** [viresh-ratnakar/exolve#13]
Further to [our discussion on reddit](https://www.reddit.com/r/crosswords/comments/dfhyet/guide_to_self_publishing_interactive_versions_of/f37zlqn/), where you said:

> If there are HTML changes that seem aesthetically better, I am happy to consider applying them to Exolve itself!

Well there is a small change I make to the body HTML in our grids that I'd forgotten about: I comment out the `<hr/>` line at 201 and the two `<br/>` lines at 209/210 (exolve-m.html v0.30) to remove the empty space between grid and clues. I guess that's created for elements we don't use, such as `exolve-question`, but I think it looks a lot better without it when it's unused. Could you maybe just insert those tags when they're required?

**Comment by viresh-ratnakar** [comment]
So, I agree about the <hr/> line, and I will just remove it.

I think the <br/> should stay: when the clues are rendered under the grid (for example, on a phone or when printing in Portrait mode), the <br/> adds welcome separation, imo. I think just one <br/> should be fine though, I can get rid of one.

**Comment by Antagony1060** [comment]
That would be great, thanks! I just didn't like the *big* gap and the line that is longer than the one above the across clues. I'm no design guru, but I though that was aesthetically unbalancing the page. :-)

**Comment by viresh-ratnakar** [comment]
Done, with v0.31.

**Comment by Antagony1060** [comment]
That's a lot better now, thanks. 

This means I've finally got the body section unchanged from exolve-m and that will make updating Exolve versions a lot easier.
