### ISSUE TITLE
'Clear this' should only clear crossing letters if the crossed entry is incomplete.

### ISSUE THREAD

**Issue by Antagony1060** [viresh-ratnakar/exolve#15]
I think most users would prefer them to be left in. But if you'd like to keep it as an option, maybe you could clear them if they're _all_ that exists? In other words, two successive clicks would clear the whole set.

**Comment by viresh-ratnakar** [comment]
Yes, seems reasonable. Will try to get to this soon.

I wish there were concise labels possible that conveyed the semantics of all these buttons clearly. ("Clear this" has these two phases, "Reveal this" also shows hints/annos, "Reveal all" also shows explanatory notes and ninas, "Check this" behaves like "Reveal this" if there is no error, etc.).

**Comment by Antagony1060** [comment]
Yeah, I guess it's one of the drawbacks of trying to cater for different needs in a logical manner. 

I've checked how the Guardian's 'Clear this' button works and it _never_ clears the crossers of completed entries. From my personal experience of using their site a lot, I can't recall ever wishing it _did_ and I'm struggling to think of a scenario where someone would. There again, I don't really use the 'Clear this' button that often anyway, as I tend to only enter answers when I'm reasonably sure about them. Still, if it were me I think I'd just program the first phase and wait to see if anyone ever asks for the second.

**Comment by viresh-ratnakar** [comment]
With v0.34, "Clear this" will only clear non-crossing letters first. If there are none, then it will clear the crossing letters.

**Comment by Antagony1060** [comment]
Hmm, that's not quite what I had in mind. I don't see any value in leaving crossers uncleared if they're not part of a completed entry. Take 15d in [this grid](https://r-crosswords.github.io/aotw/grids/grid010.html#.0000000000000.M.0.0.0.0.0.0.0O000000.0000000R.0.0.0.0.0.0.0R0000.000000000I.0.....0.0...0SPEWS.000000000D.0.N.0.0.0.0.0A000A0000.00000N...K.0.....0.0CONNECTED.00000E.U.C.0.0.0.0.0RUM0A00.0000000S.E.S.0.0.0.0.0.0N0E000000000.) for example. In my view 'Clear this' should result in S _ _ _ E | _ _ _ _ on the first click.

**Comment by viresh-ratnakar** [comment]
Ah, yes, thanks, makes sense.

Fixed now in v0.35, ptal.

**Comment by Antagony1060** [comment]
Perfect, thanks!
