### ISSUE TITLE
Multi-light entries: the input location only jumps after the first light

### ISSUE THREAD

**Issue by Antagony1060** [viresh-ratnakar/exolve#16]
In [this mini-puzzle](https://antagony.droppages.com/testing/potd004) I'm testing, where the first clue is a three word entry spanning four lights, after typing the first word input jumps to the second light as expected, but it doesn't jump again after that.

It's also drawn a couple of unnecessary line bars adjacent to black squares, so you may want to take a look at that as well.

**Comment by viresh-ratnakar** [comment]
Thanks for the catch!

Fixed with v0.38, ptal.

**Comment by Antagony1060** [comment]
Super fast response and it's working great now, thank you!
