### ISSUE TITLE
Pictures in clues, NW corner

### ISSUE THREAD

**Issue by ballantynedewolf** [viresh-ratnakar/exolve#17]
![image](https://user-images.githubusercontent.com/25334785/68805503-0e300a80-06b8-11ea-8029-26feff9cd0b1.png)
I like how this looks, but if the clue were for a light in the NW corner, I wouldn't be able to fill it in.

**Comment by viresh-ratnakar** [comment]
Can you please share the relevant lines from the exolve-across section?

It looks to me like you have an <img> tag in the clue. I can add code to look for and scrub it out for the version of the clue shown as the "current highlighted clue." However, I do not fancy that idea greatly (what else should I code to look for, for example?).

A workaround can be to include the <img> tag just above (and hence outside the clue text), like this:

exolve-across:
  ...
  15 whatever...
  <img .../>
  17 First name [of the person pictured] (5)

**Comment by ballantynedewolf** [comment]
Yes, that works. Can put the img before or after the clue and refer to it's
location or tooltip in words, only thing is that float is no longer helpful
to make it look nice. Solved that by styling the img 100% width
J


 @@-?
( -
the fashion and sober design
will make you special

**Comment by viresh-ratnakar** [comment]
Closing this issue, please reopen if needed.
