### ISSUE TITLE
How to test submit

### ISSUE THREAD

**Issue by ballantynedewolf** [viresh-ratnakar/exolve#18]
Pardon my ignorance but I need a way to test submit. I have coded exolve-submit as instructed and it works, but you seem to have made submits one-time-only and I can't work out from your code how that is done.
For me as a setter, what's the best way to be able to do several submits, eg in order to test my Google form or my correct solutions spreadsheet? I know how to use developer tools in the browser to delete a cookie but that doesn't seem to be the switch.

**Comment by viresh-ratnakar** [comment]
If you've used Google Forms, surely you can re-submit? The Exolve code does not make submits one-time-only in any way. You can try going back to the puzzle and resubmitting.

The only thing that I can think of is that if you have created a form that collects email addresses, perhaps Google Forms does not allow re-submitting? I doubt that, but in case that is so, you can make a form that does not collect email addresses, just for testing.

I can take a look at your puzzle and debug, if needed.

**Comment by ballantynedewolf** [comment]
Yes, you are right, I must have been doing something wrong. Empty light or
something?
J


 @@-?
( -
the fashion and sober design
will make you special

**Comment by viresh-ratnakar** [comment]
Closing this issue, please reopen if needed.
