### ISSUE TITLE
visually mark clues that have been filled in

### ISSUE THREAD

**Issue by martindemello** [viresh-ratnakar/exolve#19]
e.g. have a little checkmark next to the clue number if the light has been fully filled in, or change the colour of the clue text

**Comment by viresh-ratnakar** [comment]
Nice idea!

Done, in v0.39:

- When a light is filled in fully, change the colour of its clue-number. The
  colour is chosen to be a light shade of blue so that:
  - unsolved clues show with darker numbers
  - shade of blue not green as green may be construed as "correct"
    and we're not checking correctness
  - using a checkmark instead of changing the colour has tedious issues (either
    shift the clue text to make room, or worry about clipping/eclipsing).

**Comment by viresh-ratnakar** [comment]
There was a minor bug in the changes made in v0.39, fixed now in v0.40.

**Comment by Antagony1060** [comment]
I've just noticed in [this completed puzzle](https://antagony.droppages.com/potd/potd006#ESTIMATE..T.RX.R.E.H.UMBRAPOINTLESS.O.MA.N.A.B.H.NYETWIX.DELETE.S..T.P.S.R...EPSYCHE.CIRRUSI...A.U.N.E..N.ATNINE.XCIIBOP.T.W.A.U.PA.A.OUROBOROSLOREM.A.C.S.UL.T..EPISPERM) that this isn't working with linked clues.

**Comment by viresh-ratnakar** [comment]
Can you please check after updating to the latest version (now v0.42). I fixed a few corner cases for this in v0.41 and am hopeful that this one was covered (if not, will debug and fix).

**Comment by Antagony1060** [comment]
Updated and still the same I'm afraid.

**Comment by viresh-ratnakar** [comment]
OK, found and fixed this particular issue with v0.43.

**Comment by Antagony1060** [comment]
Great stuff, thanks!

**Comment by viresh-ratnakar** [comment]
Closing this (seems to be working OK now, but reopen if needed)
