### ISSUE TITLE
Linked Clues

### ISSUE THREAD

**Issue by Somsram** [viresh-ratnakar/exolve#2]
Is there a way to show linked clues in Exolve?

**Comment by viresh-ratnakar** [comment]
Yes, you can put the clue numbers of the "children" after the parent, comma
separated.

12, 14, 20 A long linked clue (4, 5, 6)
14 See 12
20 See 12

If a child clue has a different direction than the parent, you can write it
explicitly:

12, 15d A clue with mixed directions (5,7)

**Comment by viresh-ratnakar** [comment]
But please use the latest version as I added this feature after the initial
release

**Comment by viresh-ratnakar** [comment]
For completeness: :-)

If a child clue, sat 15, has a different direction, but that's the only direction for 15 (ie, only one of 15a/15d exists), then the direction will get inferred automatically --specifying it explicitly is optional)

**Comment by Somsram** [comment]
Oh Ok. thanks. Will check it out. Otherwise the software works fabulously and I am loving it :)

I think once you are fine with it, we can probably make a blogpost in one across featuring it so that more people can get to know about it.

Best regards

**Comment by Somsram** [comment]
The highlighted clue that appears on top doesn’t show the linking in enum

For eg - a clue which shows up as 30,31 in the clue area Shows up only as 30A in the highlighted area

**Comment by viresh-ratnakar** [comment]
I had chosen to show it like this (as the squares of 31 do get highlighted, which I thought was enough). However, I agree, it's more natural to show the child indices too. I've made the change, you can grab it from the latest version.

**Comment by Somsram** [comment]
Thanks 🙏
