### ISSUE TITLE
[Feature Request] Auto-reveal annotations for fully pre-filled lights.

### ISSUE THREAD

**Issue by Antagony1060** [viresh-ratnakar/exolve#20]
I was updating an ongoing competition puzzle and I wanted to see if the new entry's author had a previous entry, but the only way to tell from the UI was to select each clue one-at-a time and click 'Reveal'. It got me wondering what is the point of hiding annotations when the solutions are on display? 

I think this would also be a good feature for anyone who'd like to provide separate pages with  pre-filled solutions for their puzzles.

**Comment by viresh-ratnakar** [comment]
Sure, will add the functionality soon.

**Comment by Antagony1060** [comment]
Excellent, thank you!

Another thought I've just had: in a fully pre-filled grid there's no point displaying any of the buttons as there won't be anything to reveal or clear.

**Comment by viresh-ratnakar** [comment]
This is done, with v0.46.

Please note though:
- When a puzzle is loaded, any entry that is fully pre-filled will get its anno displayed.
- Clear this/clear all will clear the anno, if clicked. I think keeping this behaviour consistent with the non-pre-filled case is better (I for one would like the option to be able to look at clues "cleanly," without the presence of distracting annos).
- Reveal all/clear all do have additional responsibility of revealing/clearing ninas and notes if any. So, for the above reason and for this reason (and for consistency), even if there is  puzzle with all entries pre-filled, the buttons will get rendered.

**Comment by Antagony1060** [comment]
Installed and working great!

I take your point about the buttons. It hadn't occurred to me that someone might want to hide the annotation with the answer being shown, but I guess it could be a good way to test their parsing skills. 

Thanks again.
