### ISSUE TITLE
[Feature Request] Answer placeholders option for NoDir clues

### ISSUE THREAD

**Issue by Antagony1060** [viresh-ratnakar/exolve#24]
Going through some boxes in my loft the other day, I found [this old Araucaria puzzle](http://image.guardian.co.uk/sys-files/Guardian/documents/2011/03/07/gdn.cryptic.20110305_new.pdf) I'd cut out of the paper long ago and evidently forgotten about. As you can see, it is a prize 'special' that requires solving the alphabetical list of clues prior to entering them, 'jigsaw-wise', into the grid. He used to create two or three of these every year back in the day. In fact I believe he may even be credited with inventing the format.

Anyway, it got me wondering whether it would be possible to create an Exolve version of a puzzle like this, so [I had a go](https://user-images.githubusercontent.com/26671658/75624187-f9657d00-5ba9-11ea-8288-817d725a9a33.png).† Assuming I haven't missed a better way to do this, I think it kind of works but it's not quite as intuitive or convenient as I would have hoped. So I thought about what might improve it, and I reckon the ideal way would be to have answer placeholders directly underneath each related clue – so basically doing away with the need to create a separate disconnected set of questions below. 

Another nicety would be to have a little button next to the placeholders – only enabled when logically applicable – to enter the given answer into the currently selected light in the grid. 

Is this something you might consider doing? If so, from an Exolve user's perspective I think it would be most convenient to simply make it a single global option, so that every clue gets affected. Although I can imagine scenarios where one might want it for only a subset of clues, in which case it would need to be a clue-by-clue setting. 

† _In case of any copyright issues I've deleted the original interactive file and replaced the link with a picture of it instead._

---
Edit: not that you need it, but here's a mock-up picture of how I imagine it might look:
![jigsaw-sample](https://user-images.githubusercontent.com/26671658/75608200-64a14780-5af5-11ea-8477-1ab7e1be0a08.png)

**Comment by viresh-ratnakar** [comment]
Nice idea! Sure, will add this feature.

**Comment by Antagony1060** [comment]
Good man! I look forward to seeing it in implemented.

**Comment by viresh-ratnakar** [comment]
I have a draft implementation: https://viresh-ratnakar.github.io/araucaria.html
If you can play around with it to see if something looks buggy/odd, please let me know (I will release the code after trying it out like this for a bit).

**Comment by Antagony1060** [comment]
Wow, I wasn't expecting anything so quickly. You are a star!

I've had a quick play with it and it seems great so far. I've got work to do right now, but I'll check it out more thoroughly later today and get back to you.

**Comment by viresh-ratnakar** [comment]
Pls reload when you're about to play with it again (I uploaded a small fix)

**Comment by Antagony1060** [comment]
Well I had a good play with it in my lunch break and I'm very impressed with your work once again. It's already better than I envisioned and I think it's a big usability improvement when working with disconnected clues. So thank you very much for this.

Now, in the grand British tradition of never being satisfied, here are a few further thoughts I had while testing:

* I love that you've also added the placeholder text and input button to the scrolling clue list at the top, but I think it would be great if you also made *that* an input field and displayed it for every clue. That way users with small screens could enter the answers there without ever having to scroll down to the clue lists. 

* There is one small thing about the input fields that slightly bugs me – and it's the same with question inputs so probably an inherited trait – which is that the caret always jumps to the end after typing a letter. When solving the clue for, say, J1: in a normal text field I might type `L←JONA←←UR`  for JOURNAL, but with your input field you have to either solve it in your head beforehand or continuously arrow left/click inside while typing. I've noticed this only happens with valid alpha characters – not with space, backspace, hyphen, etc. – so I guess it's something about the validation process causing it.

* Also, as a keyboard nerd I dislike having to go to the mouse regularly, so it would be nice to have tab/shift-tab navigation between input fields when they're in focus. Similarly, it would be good to have the usual tab navigation within the grid when *that's* in focus.

* And one last thought I had that you might want to consideration for a future improvement:  it would be nice if entries matched between the grid and a placeholder somehow tied the clue to its entry in the grid, so that selecting one selected the other, as with normally numbered clues. 

By the way, on Sunday I started trying to construct one of these puzzles from scratch, but didn't get very far. Just filling the grid with a set of gettable answers is proving incredibly difficult. It's given me a fresh appreciation for John Graham's skill, as he seemingly knocked these out for fun at a prolific rate.

**Comment by Antagony1060** [comment]
I've just tried it again with the refresh you recommended and I see you've already got tab navigation working within the grid. So that's one of my requests already taken care of, thanks.

**Comment by viresh-ratnakar** [comment]
Thanks for the look, very helpful.

I've now uploaded v0.51. I think all the issues that you pointed out have been addressed, except the last one.

**Comment by Antagony1060** [comment]
Excellent, thank you!

I've updated my local system and it all seems good, except that tabbing within the clue list isn't quite working as I'd hoped. It moves the _highlighting_ from clue to clue, but not the input focus.

**Comment by viresh-ratnakar** [comment]
Fixed the clue list tabbing in v0.52

**Comment by Antagony1060** [comment]
Perfect!

Thanks again for all your great work and for responding so quickly and positively to requests like these.

**Comment by Antagony1060** [comment]
It's just occurred to me that providing 'solved' answers in a puzzle is is slightly problematic presently. Because, unlike with questions, there is nowhere to put the answers, except as part of annotations. Perhaps you could create a mechanism based on putting answers in curly brackets say, immediately after the enumeration – which, if present, enables the 'Reveal this' button and using that puts the answer into the input field? Just a thought…

**Comment by Antagony1060** [comment]
I've just noticed one of the recent updates has caused the overhead clue to stop displaying in [normal puzzles](https://antagony.droppages.com/potd/potd009).

**Comment by viresh-ratnakar** [comment]
Fixed with v0.54

**Comment by Antagony1060** [comment]
Great, thanks!

**Comment by viresh-ratnakar** [comment]
Please close the issue if everything looks OK. I know that there are a couple of interesting suggestions in the discussion that I haven't addressed yet, so, also fine to keep it open until I respond to them.

**Comment by Antagony1060** [comment]
Oh I'd left it open in anticipation of a response to my later suggestion for some way to provide solutions in the placeholders with the reveal button – even if it was just to say no or maybe later – but sure, I'm happy to close it for now if you prefer. 

I realise my earlier suggestion to somehow link matched answers with clues is probably a tall order and likely prone to user input errors, but I've been playing around with this new feature a lot – I've almost got a puzzle ready for publication – and the disconnectedness of the three main elements, grid, clue list, and the overhead clue bar, feels like it could be a little confusing for some users. In fact I was just thinking if only the latter two were tied together it might be enough to address that issue. 

Anyway, all of that's just food for thought and I'm very happy with what you've done so far, so I'll close this for now and leave you to mull it over.

**Comment by viresh-ratnakar** [comment]
PTAL at https://github.com/viresh-ratnakar/exolve/issues/25 that I created, thanks.

**Comment by Antagony1060** [comment]
Cheers!

By the way, in testing my now published [alphabetical jigsaw](https://antagony.droppages.com/potd/potd010) a friend said it could really do with some way to quickly distinguish which clues remain unanswered and, even more importantly, which have already been entered into the grid. I was thinking perhaps you could use a colouring scheme similar to normal grids, but as you can see I haven't used a label on the second clues for L and Y so I'm not sure how you could work around that. Something else for you to ponder… :-)

**Comment by Antagony1060** [comment]
FYI: I've changed the formerly blank clue labels in the second L and Y clues to a large bullet `[•]` so if you _do_ add any kind of label colour coding there's something to colour. Perhaps you could use this character whenever clues don't have their own label?

**Comment by viresh-ratnakar** [comment]
Thanks, I'll try to work something out.
