### ISSUE TITLE
Not working with cyrillic languages

### ISSUE THREAD

**Issue by Miskeptik** [viresh-ratnakar/exolve#26]
In cyrillic languages alphanumeric characters is from cyrillic 'А' to latin 'Z'. Something like this: а-яА-ЯёЁa-zA-Z. And so puzzle don't working with russian or ukrainian words.

**Comment by viresh-ratnakar** [comment]
Ah, yes. Thanks for filing the bug! I do hope to extend to languages beyond English when I get the time (hopefully in the not-too-distant future!).

If you have an example of a a cyrillic grid as an exolve html file that you would want to see working, please add it to this bug—it will help me.

**Comment by Miskeptik** [comment]
This is a grid with ukrainian. 
exolve-grid:
        РОКІРОВКА
        У.А.І.А.Р
        ХАЗЯЙСТВО
        .Г.Г.В.Д.
        ГАЗОБАЛОН
        .В.Д.Х.В.
        КАТАМАРАН
        У.Р.А.Е.І
        СТИСКУВАЧ


Here is the real full list of all modern cyrillic characters used in modern slavonic languages: АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯЁЂЃЄЅІЇЈЉЊЋЌЎЏҐабвгдежзийклмнопрстуфхцчшщъыьэюяёђѓєѕіїјљњћќўџґ

**Comment by viresh-ratnakar** [comment]
I've added support for Cyrillic (and for all other Scripts/languages!) in v0.70.

Please take a look. You can see an example at https://viresh-ratnakar.github.io/test-russian.html

Please also read through the new "exolve-language" and "exolve-relabel" sections in the README.md file. This is a pretty major change, and I expect that there will be some bugs/needed-improvements before the functionality is in good shape, so please let me know if you see any issues and I can try to address them. 

Thanks!

**Comment by viresh-ratnakar** [comment]
Closing the issue (please reopen if needed)
