### ISSUE TITLE
Swapped links

### ISSUE THREAD

**Issue by wpruitt14** [viresh-ratnakar/exolve#29]
Version: Exolve v0.66 April 16 2020, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0

The links for 18 and 19 across are swapped in the /r/crosswords Community AOTW Crossword 1

**Comment by viresh-ratnakar** [comment]
This is a simple issue on the AOTW site that the site's owner can fix (not an issue in the Exolve software itself). I'll message them on reddit.

**Comment by viresh-ratnakar** [comment]
I have alerted the site owner (I believe it's been fixed too, now).
