### ISSUE TITLE
Update state when a puzzle is solved/unsolved

### ISSUE THREAD

**Issue by SinghGauravKumar** [viresh-ratnakar/exolve#30]
I think a shading mechanism which shades the clue green or something to verify the clue is solved will be great. If someone messes up a solved puzzle, the state should go back to unsolved (or atleast point to the letters which are wrong.)

**Comment by viresh-ratnakar** [comment]
There is a shading mechanism already in place, to indicate that a clue has been solved: the clue number changes colour (to a light shade of blue). A setter can change this colour too, with "exolve-option: colour-solved:green" (for example).

I chose not to change the colour of the clue itself, as it makes the clue hard to read, and for simply getting an indication of whether the clue has been solved, changing the clue number's colour suffices, why make the clue harder to read! Indeed, a common scenario would be that the entered solution might be incorrect and the solver might want to read the clue again.

This colour change does depend on whether the solution is correct or not. For that, the "Check this" and "Check all" buttons are provided (but only in puzzles where the setter has included the solutions in the grid).

**Comment by SinghGauravKumar** [comment]
Okay, so I missed this part. How do I specify solutions? Also, there is a blue line on one of the grids, not sure why that happens.

**Comment by viresh-ratnakar** [comment]
You specify solutions by providing the solution letters instead of "0"s in the grid. Please go through the documentation here: https://github.com/viresh-ratnakar/exolve#exolve-grid

If your puzzle has multi-word lights with enums like (4,3) or (5-2), etc., the software draws blue lines/hyphens at the boundaries between words in such lights. Perhaps that's the blue line you saw? Otherwise please send me a a screenshot and the puzzle text itself and I can try to debug. Thanks!

**Comment by SinghGauravKumar** [comment]
Thanks @viresh-ratnakar  for the help. I prefer not to have the blue line. Let me look into it to how to get it removed. Should be an easy fix, I guess! I will close this issue, however I opened [another one](https://github.com/viresh-ratnakar/exolve/issues/31)

**Comment by viresh-ratnakar** [comment]
You can change to separator colour:

exolve-option: colour-separator:transparent

This will make the blue lines disappear. You can also change the colour to be something else you prefer.
