### ISSUE TITLE
clues-panel-lines:<N>

### ISSUE THREAD

**Issue by pourpa** [viresh-ratnakar/exolve#34]
Hi Viresh. This is a great app, thanks for doing this!
I can't seem to get exolve-option: clues-panel-lines to work..

Here is what I type:
exolve-option: clues-panel-lines:2

As soon as I insert this code, I get a mostly blank page, like the attached screenshot... I have tried v0.86 and v0.87, chrome and firefox, and a couple of different puzzles.

Hope I am not just doing something dumb..

![Jigsaw-test](https://user-images.githubusercontent.com/53801629/90456264-7d62e100-e0c6-11ea-9509-5e285498757c.png)

**Comment by viresh-ratnakar** [comment]
No, you're right! I must have broken this functionality accidentally. Will fix shortly (and will also add to my test suite). Thanks!

**Comment by viresh-ratnakar** [comment]
OK, fixed it. It was a small and quick fix, so just updated the existing latest version.

**Comment by pourpa** [comment]
wow, that was fast! yup, works now, thanks!

**Comment by viresh-ratnakar** [comment]
Closing this issue.

if you set up a site with crosswords powered by Exolve, i would love to get a link (email me at viresh at gmail dot com), thanks!

**Comment by viresh-ratnakar** [comment]
BTW, I checked in a new version (v0.88) today, which improves the scrolling behaviour when using clues-panel-lines

**Comment by pourpa** [comment]
Haha thank you. I was just about to ask about that, but you beat me to it!
Amazing work....
