### ISSUE TITLE
Add option to select no-dir-clues before Across/Down.

### ISSUE THREAD

**Issue by erikstar** [viresh-ratnakar/exolve#37]
Hi!

A Feature request which perhaps sounds a bit specialized... But for my music quizes which  try to follow swedish national radio "musikkrysset"  standard, it would be very convenient.

You can see "Sveriges Radio" solution here:
https://sverigesradio.se/sida/artikel.aspx?programid=2078&artikel=723047
And they don't even have any support for turning words entries. I have a mission to make them fix that, and one way should be to recommend them using your program. I think they have 1.7 million listeners every saturday :-)

And I think many users should miss your wonderful feature of following the no-dir-clues direction when they enter words, if they have to click three times to get to "no-dir-clues-mode"

Test:
https://fripp.changeip.org/melodikryss/melodikryss1/index_clues.html
And click on no-dir-clue 21. You need to click three times to get to the one "you want"

/Erik S

**Comment by viresh-ratnakar** [comment]
Hi Erik,

In your puzzle, the "down" lights at 1 and 21 are actually extended and supplanted by the nodir clues, right?

So, I'll create a way for you to specify that certain clues (1d and 21d in this puzzle) should be ignored: they will never get highlighted in the grid.

Additionally, I can add an option to prioritize nodir clues when having to change clue direction.

With these two, you should be able to get the behaviour that you are looking for, I think.

**Comment by erikstar** [comment]
I agree! These two fixes should be both logical and solve my "problem". Great!

**Comment by viresh-ratnakar** [comment]
I have checked in v0.89. You should be able to get these features from it.

To mark clues such as 1d and 21d as "deleted:, use something like this (https://github.com/viresh-ratnakar/exolve#deleted-clues):

exolve-down:
   1 *
  21 *

I was going to add an option to set direction priority. But I realized that this is better done by using the order of the sections as specified in the specs (it had actually been a pending thing for me to fix: if someone lists the nodir section before the down section, and both of these before the across section, for eg., then *that* should be the order shown when displaying the clues).

So, in your puzzle, just make the nodir section appear before exolve-across and exolve-down (you can leave them blank if needed). See https://github.com/viresh-ratnakar/exolve#order-of-rendered-clue-lists

**Comment by erikstar** [comment]
Just perfect! 
I use two new options together: The "~" no remove the numbering together with the "*" to skip the clue.
