### ISSUE TITLE
Feature (or external script) to clean out solutions from the html-file

### ISSUE THREAD

**Issue by erikstar** [viresh-ratnakar/exolve#41]
Hi!

I like to type in the answers during the creation phase, but then in my final version I want to just have it "clean" with zeroes.

I was just about to write a super simple pythonscript to do it, but then realized that you perhaps have some kind of solution for it.

Or can do... perhaps better that parsing  the code externally, you could create a function which exposed a  "exolve-grid" without answers. Of course not normally activated, but possible for puzzle creators to temporary activate.

perhaps this is a bit strange request... but I would be happy with it :-)

**Comment by viresh-ratnakar** [comment]
:-) I just edit the file with vi and do something like

`:30,44s/[A-Z]/0/g
`

**Comment by erikstar** [comment]
OK. I would love to show a shorter version with my emacs :-) But I think you win! 
OK. I can live without it,,,

**Comment by erikstar** [comment]
I agree. Meaningless...
