### ISSUE TITLE
Hiding buttons Option

### ISSUE THREAD

**Issue by lenniebriscoe** [viresh-ratnakar/exolve#43]
I would like someone to complete the crossword without providing them with the ability to reveal the solution. Is it possible to allow individual buttons (including "Reveal this" and "Reveal All!") to be hidden, please?

eg
exolve-option: btn-reveal-this-visible:false btn-reveal-all-visible:false

**Comment by lenniebriscoe** [comment]
I have done this with CSS:
#xlv1-reveal {
  visibility: hidden;
}

#xlv1-reveal-all {
  visibility: hidden;
}

**Comment by viresh-ratnakar** [comment]
Also, if you replace all the solution letters in the grid with 0s, the reveal buttons do not get shown.

Look for "Grid without solutions" in https://github.com/viresh-ratnakar/exolve#exolve-grid
