### ISSUE TITLE
Making Window alerts optional

### ISSUE THREAD

**Issue by lenniebriscoe** [viresh-ratnakar/exolve#47]
Sometimes I would like the user to click one of the buttons but there not to be a window alert (message box popup). I intend to alert the user on the screen via markup. Is it possible please that if the relabel option is empty then you skip the alert()?

example:

```
exolve-relabel:
    confirm-check-all:
```

**Comment by viresh-ratnakar** [comment]
Sure, will get to this in the next version.

**Comment by viresh-ratnakar** [comment]
I've done this now, in v0.95. If a confirm-* message is relabeled as empty, that alert is skipped.

**Comment by viresh-ratnakar** [comment]
Closing out old bugs that I did take some action on. If I haven't fixed every aspect as expected, apologies, but please open a new bug (hard for me to parse out what remains to be fixed).
