### ISSUE TITLE
hyphen in nodir clues?

### ISSUE THREAD

**Issue by erikstar** [viresh-ratnakar/exolve#48]
Relates to #40 (well actually was part 3 in that)

I realized it is a bit strange question for the generic "nodir", but for my only use of "nodir" it makes sense -- the "turning words".

So ideal this should be my suggested behaviour:

The same way of notation for hyphens Example (9-1-3), but the hyphen should only be placed if the next square is beside the "current" square.

So in my 9x10: https://fripp.changeip.org/melodikryss/melodikryss2/lost2.html

 #a7 #b7 #c7 #d7 #e7 #f7 #g7 #h7 #i7 #j7 #j6 #j5 #j4 [] (9-1-3)

(The long turning word with number 8 if you check the link.)

I would like to have two hyphens -- one across and one down.

I understand it would perhaps give a lot of extra work I am the only one asking for... but it would be elegant :-)

**Comment by erikstar** [comment]
An alternative implementation. Not at all that elegant, but it should do for me!

It is that it should be possible to add hyphens in "deleted" clues.

The same example (https://fripp.changeip.org/melodikryss/melodikryss2/lost2.html)
I use 
exolve-down:
   #j7 [] *
To skip "down only-part" of my long turning word to get pinkish...
If I write  #j7 [] (1-3) *
the hyphens works perfect, (because it is not handled "deleted").
So if you are in no mood for the real implementation of this esoteric demand perhaps you could make #j7 [] (1-3) *
place the hyphes, but still act as deleted

**Comment by viresh-ratnakar** [comment]
Not sure I understand fully with a quick read, but I will try to do something for this bug as a top priority, in the next version that I put out :-). Thanks for your patience!

**Comment by viresh-ratnakar** [comment]
I added the ability to force hyphens/bars to the right of or below any cell, with v0.95.

Eg.:
```
  exolve-force-hyphen-right: a5 c4
```

Please see for more details.

https://github.com/viresh-ratnakar/exolve/blob/master/README.md#exolve-force-hyphen-right-exolve-force-hyphen-below-exolve-force-bar-right-exolve-force-bar-below

Further, the way to link nodir clues is like this (this was already the case):

```
   exolve-nodir: 
    #a7 #b7 #c7 #d7 #e7 #f7 #g7 #h7 #i7 #j7 #j6 #j5 #j4 [8] See 9.
    #d4 #e4 #f4 #g4 #h4 #h3 #h2 #h1 [13] See 9.
    #a5 #a4 #a3 #a2 #a1 #b1 #c1 [9], [13], [8] Clue
```

**Comment by erikstar** [comment]
Fantastico! Thanks. Embarrasing that I didn't  understand  the "See-concept"
