### ISSUE TITLE
Howto group a couple of "nodir-clues"?

### ISSUE THREAD

**Issue by erikstar** [viresh-ratnakar/exolve#49]
I tried different ways... But I only managed to get it work with ONE nodir followed by across and down.

This works:
exolve-nodir:
 #d4 #e4 #f4 #g4 #h4 #h3 #h2 #h1 #a5 #a4 #a3 #a2 #a1 #b1 #c1 [8], 15a ()

but how to do something like this:
exolve-nodir:
#d4 #e4 #f4 #g4 #h4 #h3 #h2 #h1 #a5 #a4 #a3 #a2 #a1 #b1 #c1 [8], #a7 #b7 #c7 #d7 #e7 #f7 #g7 #h7 #i7 #j7 #j6 #j5 #j4 [13] 
?

**Comment by viresh-ratnakar** [comment]
In this case, why does the nodir clue [13] need to exist at all if it's only a part of [8]? Normally, for a "child" clue, all you would say is something like "See ...(parent clue number)..." which makes sense if the child clue is for a light created by the grid, like an across or down clue.

I mean, why not just do:
exolve-nodir:
#d4 #e4 #f4 #g4 #h4 #h3 #h2 #h1 #a5 #a4 #a3 #a2 #a1 #b1 #c1 #a7 #b7 #c7 #d7 #e7 #f7 #g7 #h7 #i7 #j7 #j6 #j5 #j4 [8], ...

Perhaps I'm missing something :-).. you can point me to an example, perhaps?

**Comment by erikstar** [comment]
Perhaps it all makes more sens if I make a super concrete example. This is a fully working "music quiz" (in swedish :-) 
copying swedish national radio concept since the 60-ties. (https://fripp.changeip.org/melodikryss/melodikryss2)

So originally you had this "crossword" published in newspapers and every saturday you listen on the radio and solve it. 

So the order of "what to solve" was kind of decided of the speaker/creator.

So in my example  I say (15 minutes in the ogg)  "Now we have 9 down (turning word), 13 across (turning word) and 15 across". We will listen to a song bla bla bla, and I want to have in order "the TV-show this was a theme", "The composer last name", "the composer first name".

So in this example I have three different "lights" (?... I am really not a crossword person... and not good at english..) for ONE song/multi question. So for me it makes sens to have reference numbers for both 9d (turning) and 13a (turning).  And this is how swedish "melodikryss" from national radio handles it.

As you perhaps understand it can be a bit thrilling to remember three different places on the bord when you listen to the question, so that is the reason I think it is brilliant to group them together. When you use the old shchool way on paper I guess the normal procedure is to mark the three lights with pencil when the the question starts.

techically I solved it in the way you suggested. It is just one long: 
#d4 #e4 #f4 #g4 #h4 #h3 #h2 #h1  #a5 #a4 #a3 #a2 #a1 #b1 #c1 [], 15a ()

But I pretend it is two different... As long as I hide the xlv1-clues and 
xlv1-curr-clue-parent (as you helped me with) it doesn't matter much. 
And here my simplified handeling of the lights number (the "[]" at my nodir-lights) doesn't matter much.

But as you can see in my initial experiment
with possibilities to control the listening. (https://fripp.changeip.org/melodikryss/melodikryss2/lost.html), you can see that this will be a bit more important.
No problem for me to include the 9 and 15 in the nodir-questions, but still... I also want the 13 in some way.

Hopefully this makes my demands a bit clearer...

Thanks again!
/Erik S

**Comment by erikstar** [comment]
It was me not understanding the see-concept
