### ISSUE TITLE
Puzzle prints incompletely from Edge

### ISSUE THREAD

**Issue by Raceous** [viresh-ratnakar/exolve#5]
Version: exolve v0.15 August 5 2019, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134

When attempting to print a puzzle from the Edge browser, the Print Preview shows only the first page, or the first page and a few lines of the second page. So some or all of the questions and clues are omitted.

Different results can be obtained by changing the settings in Edge's print dialog (namely Orientation, Scale, Margins). At 50% scale, usually the whole puzzle fits on one page and prints completely. However, 50% results in unpleasantly small type. 75% scale results in a pleasant size, but truncated printing, as described above. (Unfortunately Edge does not allow scales in between 50% and 75%.)

The most desirable behavior would be for exolve to provide a "print view" of a puzzle that is laid out to fit on one page in most cases. For example, to save space, the introductory text could be tighter spaced and the questions could be to the right of the grid.

**Comment by Raceous** [comment]
I have found a workaround that gets the header, grid and clues, though not the questions, onto one page at 75% scale. Choose Landscape orientation and Narrow margins, and set the paper size to Legal, even if the printer is actually loaded with Letter size paper. Attached is a screenshot of the Print Preview dialog.
![Workaround print dialog](https://user-images.githubusercontent.com/54013910/62991132-4139d800-be03-11e9-8c04-f0c6327e5436.png)

**Comment by viresh-ratnakar** [comment]
I've made some tweaks in v0.29 to get better printing on Chrome. I don't have access to Edge currently, but if someone can check if it improves things, I would appreciate it! (An example grid to test with: https://viresh-ratnakar.github.io/gussalufz-14-unsolved.html).

Yes, I did get rid of "questions" section altogether for printing. Unfortunately they get in the way of one-page rendering (esp in Portrait mode), and I do think that having them on the printed page is not terribly important.

**Comment by viresh-ratnakar** [comment]
Is this still an issue in Edge, or is it reasonably OK with the workaround?

**Comment by Raceous** [comment]
I haven't bothered to print the puzzles in several months, as I've grown to enjoy solving them on exolve directly. So yes, the workaround is good enough. Another workaround is to take a screenshot of the puzzle and print that.

**Comment by viresh-ratnakar** [comment]
Thanks, closing this too.
