### ISSUE TITLE
Firefox for Android jumps forward one extra step on typing

### ISSUE THREAD

**Issue by erikstar** [viresh-ratnakar/exolve#52]
Tested on Sony Xperia 10II with Android 10 and Firefox 82.1.1 and 83.0.0 beta

**Comment by viresh-ratnakar** [comment]
Please see https://github.com/viresh-ratnakar/exolve/issues/8

This is a known issue, and unfortunately I do not have any good ideas on how to fix without adding browser-specific workaround code that I'm reluctant to do.

The ideal thing to do would be to track down the issue in Firefox code itself and get it fixed there :-). If/when I get the time, I'll try to do a bit more research.

**Comment by viresh-ratnakar** [comment]
Closing out old bugs that I did take some action on. If I haven't fixed every aspect as expected, apologies, but please open a new bug (hard for me to parse out what remains to be fixed).
