### ISSUE TITLE
Grid numbering issue for an Across clue having One word answer 

### ISSUE THREAD

**Issue by msayali** [viresh-ratnakar/exolve#53]
Version: Exolve v0.96 October 18 2020, User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36

Excellent creation and is very helpful, easy to put our crossword.
But we have encountered here a special case as below -
If the across word has clue having one word answer, this tool skips that number causing wrong numbering of grid. How to correct this scenario?

**Comment by viresh-ratnakar** [comment]
Sorry, I don't quite understand. Perhaps you can copy your puzzle specs here in the bug?

**Comment by msayali** [comment]
Thanks for you quick response. 
I have a 22 x 22 cross word in Devanagari. I have marked the position bold in the exolve-grid below where I expect the grid number to be 64 (for the 64 across) 
But, I see that it skips that position and wondering if it is because the answer is only 1 letter long?
Due to this all the number after that are skewed and not where they are supposed to be.
You can see that because of that the crossword end at 103 across on the grid where as I have till 105 across
  
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<link rel="stylesheet" type="text/css" href="exolve-m.css?v0.96"/>
<script src="exolve-m.js?v0.96"></script>

<title>Hindi</title>

</head>
<body>
<script>
createExolve(`
======REPLACE WITH YOUR PUZZLE BELOW======

exolve-begin
  exolve-id: test
  exolve-title: Test 22 x 22
  exolve-setter:
  exolve-copyright:
  exolve-width: 22
  exolve-height: 22
  exolve-option: colour-active:lightyellow colour-input:palegreen
  exolve-option: colour-arrow:gray color-small-button-hover:palegreen
  exolve-language: hi Devanagari
  exolve-relabel:
    setter-by:
    across-label: across
    down-label: down
    clear: Clear
    clear.hover: Hindi me likha hai, Clear this!
    clear-all: Clear All
    reveal: Show Answer
    reveal-all: Show All Answers
    reveal-all.hover: Hindi me likha hai, Reveal all!
    across-letter:
    down-letter:
    placeholder.hover: Yahan likho
    placeholder-copy.hover: Copy karo
    confirm-mismatched-copy: Itno se itne tak?
  exolve-prelude:
  exolve-grid:
    0 0 0 0 0 0 . 0 . 0 . 0 0 0 0 0 0 0 0 0 0 0
    0 . 0 . 0 . 0 0 0 0 0 . . 0 . . 0 0 . . . 0
    0 . 0 0 0 0 . 0 . 0 . 0 . . . 0 . . 0 0 0 0
    0 . . . . . . 0 . 0 0 0 0 0 0 0 0 0 0 . . 0
    0 0 0 0 0 0 0 0 . 0 0 . . 0 . . 0 . 0 . 0 0
    0 . 0 . . 0 . . 0 0 . 0 0 0 0 0 . . 0 . 0 .
    0 0 0 . 0 0 0 0 0 .  0 . . 0 . . . 0 0 0 0 .
    0 0 0 . . 0 . 0 . 0 0 0 0 0 0 0 0 0 0 . 0 .
    0 . . 0 . 0 . 0 . . 0 . . . . 0 . 0 . 0 0 0
    0 0 . 0 0 . 0 . 0 0 . 0 0 . 0 0 . . 0 0 . 0
    0 . 0 . 0 . 0 0 0 . 0 0 . 0 . 0 0 . 0 0 . .
    0 0 0 0 0 0 0 . 0 . 0 0 0 0 . 0 0 0 . 0 0 0
    0 . 0 . 0 . . 0 0 . 0 . 0 0 . 0 . . 0 0 . .
    0 . 0 . . 0 . . 0 . **0** . . 0 . 0 0 . . 0 0 .
    . 0 0 0 0 0 0 . 0 . 0 0 0 . 0 . . 0 . 0 0 .
    . . 0 . 0 0 . 0 0 0 0 . 0 . 0 0 0 0 0 0 . .
    0 0 0 . . . 0 . 0 . 0 . . 0 0 0 . . 0 .  0 .
    0 . . 0 .  0 0 0 0 . 0 0 0 . 0 . . 0 0 0 0 0
    0 0 0 0 . 0 . . 0 . 0 . . 0 0 0 . . 0 0 . 0
    0 . . 0 . 0 . 0 0 0 . 0 0 . 0 . . . 0 . 0 0
    0 . 0 0 0 0 0 . . 0 . . 0 0 . 0 0 . 0 0 0 .
    0 . .  0 .  0 . 0 0 0 0 0 0 0 0 0 . 0 . . 0 0

  exolve-across:
  1 test
  6 test
  11 test
  12 test
  13 test
  16 test
  17 test
  21 test
  24 test
  25 test
  26 test
  27 test
  28 test
  30 test
  33 test
  34 test
  35 test
  38 test
  40 test
  41 test
  44 test
  45 test
  46 test
  47 test
  49 test
  50 test
  52 test
  54 test
  55 test
  56 test
  58 test
  59 test
  60 test
  61 test
  62 test
  64 test
  65 test
  66 test
  68 test
  70 test
  74 test
  75 test
  76 test
  77 test
  80 test
  82 test
  85 test
  86 test
  87 test
  90 test
  91 test
  92 test
  93 test
  95 test
  97 test
  98 test
  99 test
  101 test
  102 test
  103 test
  104 test
  105 test

  exolve-down:
  1 test
  2 test
  3 test
  4 test
  5 test
  7 test
  8 test
  9 test
  10 test
  14 test
  15 test
  16 test
  18 test
  19 test
  20 test
  22 test
  23 test
  25 test
  26 test
  29 test
  31 test
  32 test
  33 test
  36 test
  37 test
  38 test
  39 test
  42 test
  43 test
  44 test
  45 test
  47 test
  48 test
  50 test
  51 test
  53 test
  57 test
  63 test
  67 test
  69 test
  71 test
  72 test
  73 test
  78 test
  79 test
  80 test
  81 test
  83 test
  84 test
  85 test
  88 test
  89 test
  94 test
  97 test
  100 test
  101 test

  exolve-nodir:
exolve-end

======REPLACE WITH YOUR PUZZLE ABOVE======
`);
</script>
</body>
</html>

**Comment by msayali** [comment]
I did read through the instructions around possible issues for wordpress and wondering if you might have any suggestion for wordpress rendering.

**Comment by viresh-ratnakar** [comment]
1-letter words are generally not supported in crosswords, but I'll try to figure out  a way for you. Am a bit swamped at the moment though, so may take a while for me to get to it.

Re: wordpress: if you pay them, I think you can set up JavaScript in your pages (but I haven't tried it). Consider creating a blogger page and linking to it.

Also, the test Hindi file that I have checked in uses pretty random text, I wrote it only for testing. You probably want to set the entries in "exolve-relabel" to some reasonable values.

**Comment by msayali** [comment]
Nice. That would be great. We decided meanwhile to take out the 1-letter words from the crossword and the rest is working like a charm. Also have been able to put it on wordpress by having css and js using custom snippets.

**Comment by viresh-ratnakar** [comment]
OK. BTW, if this Hindi crossword is accessible by anyone, I would love to get a link and take a look, thanks.

**Comment by msayali** [comment]
Here is a draft link where you can see it in action https://t2.mazamarathichabol.org/shabdkode/
WiIll need to scroll down tot view it as there is some issue with rendering in the current wordpress theme in terms of priority so loads after footer :)

**Comment by viresh-ratnakar** [comment]
Thanks for the link, looks great!

I think, "one-letter clues" are really going to complicate the code, so unfortunately I'll skip adding support for them.
