### ISSUE TITLE
Not an issue, just a congratulation

### ISSUE THREAD

**Issue by ballantynedewolf** [viresh-ratnakar/exolve#54]
Viresh, you bloody legend.
A year after making my last crossword with exolve 0.23, I'm making another one and I think better check for an update and I see you've been hard at work making this already amazing app even better.
Good onya!
Jona

**Comment by viresh-ratnakar** [comment]
Thanks!

I've also been working on a companion software called "Exet," which is a grid construction web app. You can create crosswords and save as Exolve as well as .puz. Please give it a shot if you find the time, at: http://exet.app (the github project is at https://github.com/viresh-ratnakar/exet).

**Comment by ballantynedewolf** [comment]
Love to. I use qxw and while it's good there's not an easy way to port it
into exolve.
Jona

#please note my email address has changed:
- jonathan@wolfchart.org (general)
- jonathan.sykes.globe5@gmail.com (fire brigade matters)

Jonathan Sykes
+61404719997

**Comment by ballantynedewolf** [comment]
I just used exet/exolve to make a test widget crossword for a blog.
Brilliant, a total breeze.
I have a couple of suggestions, non critical:


   1. Is it explicit enough for those installing locally that exet and
   exolve share common files? It's good that you direct people to the console
   for help, but the console doesn't tell you where to obtain the missing
   files. Good use for promise syntax?
   2. I think it's generally good UX to show an alert if something is
   copied to your clipboard (Exet save menu), in case they had clipboard
   contents related to this same task eg a destination email address, that
   you've now overwritten.
   3. Let's say you want to use the widget method, but you want to host
   your own js and css files. Could you have a couple of text boxes for the
   urls of those resources that replace your hosted links in the widget
   snippet? Maybe as part of a preferences menu?

Once again, congratulations on your very powerful and elegant apps.
Jonathan


  @@-?
( -
the fashion and sober design
will make you special



  @@-?
( -
the fashion and sober design
will make you special

**Comment by viresh-ratnakar** [comment]
I did #2. For #1 I'm not quite sure what you mean (I think all the files mentioned have links... what did I miss?). For #3 hmm: it's easy enough to edit the plain text exolve file/code to do this. I'm not sure the added complexity is warranted. But we can discuss.

I'm closing this bug (thx again for all the kind words!). Please feel free to open Exet-specific new issues in Exet (https://github.com/viresh-ratnakar/exet) rather than here.
