### ISSUE TITLE
Responsive View

### ISSUE THREAD

**Issue by lenniebriscoe** [viresh-ratnakar/exolve#55]
Is it possible to have a focused\responsive view in addition for smaller screen sizes please? When I view my crossword on a small screen the clues wrap nicely under the crossword, but the crossword itself is too wide for the screen which creates horizontal scrolling. The individual boxes then become quite small to click on. It might be good to be able to zoom in to each word in full screen and then be able to navigate from word to word displaying the associated clue underneath. 
Thanks

**Comment by viresh-ratnakar** [comment]
I have extended the responsive view to smaller screens, with v1.01. PTAL. Haven't added the zoom feature that you've described though.
