### ISSUE TITLE
Change font size of Preamble and Clues in widget

### ISSUE THREAD

**Issue by ballantynedewolf** [viresh-ratnakar/exolve#56]
Using the full html file version, I can change the font-size of both preamble and clues by doing this:
function customizeExolve(p) {
    p.frame.style.fontSize="13pt";
  }

However if I do the same in a widget, only the preamble has the 13pt text

What's the best way to increase font-size in elements other than the grid?

**Comment by viresh-ratnakar** [comment]
Can you point me to a URL where you see this? I suspect this is some css inheritance issue that can be fixed.

**Comment by ballantynedewolf** [comment]
sorry to be so long replying. I tested this again and now it works, so either I misread the situation or you've fixed it in the [long] interim.
Thanks
