### ISSUE TITLE
Linting / ES6 / npm support

### ISSUE THREAD

**Issue by lenniebriscoe** [viresh-ratnakar/exolve#57]
Dear Santa, 

It would be great if you could:
1) run the code through a linter to tidy up the code. It's sending my linter mad so I had to disable it for this package.
2) modularise it and export the objects\functions so that it isn't on the Global namespace and also can be used easily in ES2015 etc projects i.e. import {createExolve} from 'exolve-m' and then magically bundled using webpack.
3) publish it to npm so that I can "npm install" the package and reference it 

My front end skills aren't great, but if you can already do the above it would be great to add instructions into the readme.

Thanks!

**Comment by viresh-ratnakar** [comment]
I understand #1, but don't know yet what's an easy way for me to do this (I use vim.. there probably is some linter that I can integrate.. suggestions are welcome!).

Parts of #2 and all of #3 are Greek to me :-). Will try to educate myself more.

**Comment by viresh-ratnakar** [comment]
With v0.97, I've now at least got all lines to be <= 80 columns.

**Comment by viresh-ratnakar** [comment]
Given that over 4ish months of occasionally staring at this bug, I haven't really connected with it :-), I think I will close this issue soon. I'm sure node.js and npm are lovely, but I'm getting old and am a bit reluctant to learn about packages and frameworks.

Linting, otoh, I do agree with. I've been trying to clean things up towards that (80 cols max, for eg.) and will continue to do so.
