### ISSUE TITLE
‘Check this’ not working on one particular correct solution

### ISSUE THREAD

**Issue by Antagony1060** [viresh-ratnakar/exolve#62]
I'm hosting [this new puzzle](https://antagony.droppages.com/potd/potd029) for another redditor, but Exolve doesn't seem to like 13d for some reason – is it superstitious? :\^). Reveal operations were initially showing the anno without the solution, so I added it explicitly in square brackets. That fixed that problem, but I'm still finding that even with the correct answer entered (see below) the clue number doesn't turn blue and Check this doesn't do anything. The Reveal buttons both work fine AFAICT. But, after pressing Reveal all then refreshing the page 13d loses it's blue clue number again.

<details><summary>13d answer SPOILER</summary><pre>PETRI</pre></details>

**Comment by viresh-ratnakar** [comment]
I was hoping this would be a deep bug that would be satisfying to solve and good to get rid of :-), but unfortunately it's simply a case of an incorrect enum—should be (5) not (6). With (6), Exolve thinks it does not know where all the cells for this special clue are, so it has trouble with check/reveal/etc.

You can also remove the square-bracketed solution after fixing the enum.

I don't want to add an automated-check+warning for the provided enums not matching light lengths (as there can be deliberate instances of that if the setter wants to use some kind of ruse). But perhaps I'll add a feature buried under Tools to identify any clues that seem to have mismatched enums.

**Comment by Antagony1060** [comment]
Damn, I should have noticed that! Thanks for looking into it so quickly and letting me know what the problem was. 

And yeah, it wouldn't be a bad idea to have some kind of enum integrity check hidden away somewhere. It's an easy mistake to make but a chore to check manually.
