### ISSUE TITLE
Feature request: separate "reveal/check cell/word/all" buttons?

### ISSUE THREAD

**Issue by eigenfoo** [viresh-ratnakar/exolve#66]
I know that holding down on the "Check/Reveal this" buttons will give me a "Check/Reveal cell", but this seems unintuitive for new users, who either need to know Exolve beforehand, or hover over the buttons for instructions (which seems like an odd way of teaching users this functionality?)

It would be nice one of the following could happen:

1. Have two buttons "Check" and "Reveal" that become drop-down menus allowing you to choose between "Cell", "Word" or "All", similar to how [Amuselab's interface, for example](https://amuselabs.com/pmm/crossword?id=d8b32d70&set=1383102e08ed60ddd50b4a1517cee19c96ce58fd08d719536855e37adfdeecf4)
2. Have each button on its own (perhaps making the buttons smaller so they don't take up as much space?), for a total of six buttons (plus the "Clear" buttons)

I'm not sure how feasible/easy to implement this would be, but am interested in hearing thoughts?

**Comment by viresh-ratnakar** [comment]
Hi @eigenfoo,

Thanks for the suggestion!

I'm not a huge fan of 1. as it seems to make a simple task like "Check this" / "Clear this" a bit of a chore.

I'll try out the extra two buttons and play with the possibilities a bit. One thought is to give the setter/designer control through options on what buttons to create, and to also give the solver the option to state their own preferences (in a sticky way across puzzles, within the same browser)

**Comment by eigenfoo** [comment]
Thanks for the consideration!

I agree that having a drop-down menu disrupts the solving experience. I also like the idea of allowing setters/designers to modify the buttons, but allowing users to modify buttons strikes me as overkill: as a crossword solver I mostly care about the crossword, and having the option to customize my solving experience seems like an nice but unneeded distraction (although perhaps it's just me!).

In any case, thanks for considering this request, and I look forward to seeing what you choose!

**Comment by viresh-ratnakar** [comment]
I have added `exolve-option: show-cell-level-buttons` with v1.15, ptal.

**Comment by eigenfoo** [comment]
This is great! I've already included it in my site. Thanks so much for the quick response!

**Comment by eigenfoo** [comment]
By the way - how can I best support this project? Is there a need for open-source contributions, or do you have a tip jar somewhere?

**Comment by viresh-ratnakar** [comment]
Re: supporting the project: tips are not needed, contributions are not necessary (but I welcome ideas/discussions)!

The best support would be to publicize/promote Exolve (and Exet!), getting more users to adopt :-) . Thanks!
