### ISSUE TITLE
Allow clue numbers to have a . after them

### ISSUE THREAD

**Issue by martindemello** [viresh-ratnakar/exolve#7]
Version: Exolve v0.18 August 23 2019, User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0

it seems like a natural thing to do when writing the clues out in a text file.

**Comment by viresh-ratnakar** [comment]
Done in v0.19, please check.

**Comment by martindemello** [comment]
yep, works great!
