### ISSUE TITLE
clues-panel-lines causes layout errors in printing

### ISSUE THREAD

**Issue by DKMiller71** [viresh-ratnakar/exolve#71]
When using  **exolve-option: clues-panel-lines**, the Down clues appear to overlap atop the Across clues.  It's particularly bad with Chrome.  Only slightly bad in FF.

**Comment by viresh-ratnakar** [comment]
Thanks, nice catch! Will try to fix asap.

**Comment by viresh-ratnakar** [comment]
I have pushed a quick fix to this, PTAL.

https://github.com/viresh-ratnakar/exolve/commit/7fef64e7fd81b8778aa2cf075aa8796114f4f469

**Comment by DKMiller71** [comment]
Looks good!
