### ISSUE TITLE
Selected square is highlighted when printing

### ISSUE THREAD

**Issue by DKMiller71** [viresh-ratnakar/exolve#73]
When printing the grid, the currently selected square is still highlighted.  I think the selection highlight should be ignored for print purposes.

**Comment by viresh-ratnakar** [comment]
Thanks, I'll fix soon!

**Comment by viresh-ratnakar** [comment]
This is fixed now in v1.21 that I just checked in.

**Comment by DKMiller71** [comment]
Per my note on your "larger grid" fix, the new print layout causes
formatting issues, including the grid overlapping the third column, the
columns running off the page, and extra blank before 36D.  Attached is an
example.

The 2-col layout (with exolve-option: print-incomplete-2cols) looks normal
(and the highlighted square has been cleared).
