### ISSUE TITLE
Little mistakes in section exolve-relabel in README

### ISSUE THREAD

**Issue by PedroBlanco** [viresh-ratnakar/exolve#78]
In section [exolve-relabel](https://github.com/viresh-ratnakar/exolve#exolve-relabel):

- `manage-storage-hover` should be `manage-storage.hover`
- `manage-storage-close-hover` should be `manage-storage-close.hover`

**Comment by viresh-ratnakar** [comment]
Thanks for catching!

Have fixed these with https://github.com/viresh-ratnakar/exolve/commit/6f81b9ae3d01928de80a2c11355854286c06a18b

**Comment by PedroBlanco** [comment]
Thanks for this awesome software!
