### ISSUE TITLE
How to make gridlines thicker?

### ISSUE THREAD

**Issue by SinghGauravKumar** [viresh-ratnakar/exolve#88]
As the issue title suggests, I want to make the gridlines of the crossword slightly thicker. How do I go about doing that?

A side issue, is how do I hide the links and the message as shown in the screenshot below?

![image](https://user-images.githubusercontent.com/12415994/221365698-fb663692-b925-4322-b009-3095a7e41c73.png)

**Comment by viresh-ratnakar** [comment]
I've added an option now to override any numeric property. The thickness of the line is controlled by the property named 'GRIDLINE`, so you can do something like:

```
  exolve-option: override-number-GRIDLINE:1.6
```

You can see how this looks in [this demo](https://viresh-ratnakar.github.io/test-override-number.html).

As for hiding elements like the ones you show: you can right-click and inspect to find their IDs, and then hide them from a `customizeExolve()` function. The IDs are all of the form `<prefix>-<name>` (such as `xlv1-saving` and `xlv1-small-print`).

So, for example, to hide the auto-save message and the links to Exolve/Print/Notes:

```
function customizeExolve(puz) {
  document.getElementById(puz.prefix + '-saving').style.display = 'none';
  document.getElementById(puz.prefix + '-small-print').style.display = 'none';
}
```

I will say that the saving message and the Exolve links are generally useful to solvers and I would not recommend removing them. Also, while the Exolve software gives you the permission to use it in any way you like and to tweak it in any way you like, it would be nice to retain a link to it to acknowledge that you've used it and to let other potential users find it. Of course, ultimately it's all your call.

**Comment by SinghGauravKumar** [comment]
Absolutely. I am giving credit and telling everyone about exolve in the beginning of the page, followed by dozens of crosswords in the same page , instead of one crossword per page.
