### ISSUE TITLE
This app is amazing, thank you

### ISSUE THREAD

**Issue by ballantynedewolf** [viresh-ratnakar/exolve#9]
Can I ask, why is the grid definition appended to the URL?
Ballantyne

**Comment by ballantynedewolf** [comment]
And another question: why are annotations not available from Reveal This, only from Reveal All?

**Comment by viresh-ratnakar** [comment]
Thanks for the kind words about Exolve!

> Can I ask, why is the grid definition appended to the URL?

The current solution state is saved and updated in the URL, so you can
bookmark or otherwise save the URL to capture your state (and can open the
URL on another device to transfer state). The state is also saved in a
cookie, but that has some issues (cookie limits, auto-deletions), so I
found it safer to also save in the URL.
https://github.com/viresh-ratnakar/exolve/blob/master/README.md#saving-state


On Tue, Sep 24, 2019 at 11:52 PM ballantynedewolf <notifications@github.com>
wrote:

> And another question: why are annotations not available from Reveal This,
> only from Reveal All?
>

That's a good point. I'll try to fix this.

**Comment by viresh-ratnakar** [comment]
"Reveal/Clear this" now shows/clears the annotation (if available) for the clues associated with the current cell, in version v0.24.

**Comment by Antagony1060** [comment]
I've just started experimenting with adding annotations, and I'm very impressed once again. One thing I think would be an improvement, though, is having the 'Check' buttons also reveal the annotation, but only for correct answers.

**Comment by ballantynedewolf** [comment]
Thanks. I should've read your docs more closely! I was just so excited by
how perfect the app is.😁
Jonathan

**Comment by viresh-ratnakar** [comment]
With v0.25 now, "Check this" and "Check all" do everything that "Reveal this" and "Reveal all" do, if they find no errors.

For "Check all" this is slightly different from what Antagony1060 requested (as it will not reveal annos for correct entries if there is a mistake elsewhere), but was easier to implement.

**Comment by ballantynedewolf** [comment]
Enjoying the updates in 0.26. This is a very good app IMO.

Can I suggest a feature: a text box for typing in anagram fodder, with a
Fisher-Yates shuffle function called by an html button. Solvers can then
shuffle the letters til they get some inspiration.

Jonathan


 @@-?
( -
the fashion and sober design
will make you special

**Comment by viresh-ratnakar** [comment]
Sure, will add an option to create this.

**Comment by viresh-ratnakar** [comment]
I added a scratch pad in v0.27 (with an control to shuffle the selected text in it -- or all text if none has been selected).

The scratch pad is hidden, but can be toggled with the "Tools" link (I renamed the erstwhile "Controls" link to "Tools," reusing it for this).

There are tooltips that describe the functionality on hovering over the Tools link as well as the Shuffle control.

**Comment by viresh-ratnakar** [comment]
Closing this issue, please reopen if needed.
