### ISSUE TITLE
Feature Request: Annotation column next to clues

### ISSUE THREAD

**Issue by martindemello** [viresh-ratnakar/exolve#90]
Variety crosswords often have a gimmick like "drop a word from every clue before solving, initial letters of dropped words spell out an instruction". It would be helpful if exolve had a column before the clues where solvers could record things like this as they go.

It would also help for skeleton crosswords where you need to write the clue answers somewhere other than the grid until you figure the grid out.

**Comment by martindemello** [comment]
oh nice, missed that! i still think a column would be nice in addition - when i'm doing crosswords i tend to write the answer after the clue but any extractions before it so that i can easily read down the column.

**Comment by viresh-ratnakar** [comment]
I like the idea. I've implemented it and will push an update soon (after some more testing).

You can try it right now if you like, by pointing at dev versions of the files:

```
<link rel="stylesheet" type="text/css" href="https://viresh-ratnakar.github.io/dev/exolve-m.css"/>
<script src="https://viresh-ratnakar.github.io/dev/exolve-m.js"></script>
```

Here's the documentation that's getting added:

### Adding "extraction slots" before clues

A common ruse in cryptics is to make each clue somehow yield an extra letter 
and to make a meta out of those letters. Exolve allows you to add a column
of "extraction slots" before each clue. Solvers can record letters/numbers
in these slots (and these are saved in the state too). You can do this
by specifying `exolve-option: add-extraction-slots`. By default, if you
specify this option, then a *one*-letter slot is added. But you can specify
the number of letters in the slot with an optional parameter (e.g.,
`exolve-option: add-extraction-slots:3`).

**Comment by viresh-ratnakar** [comment]
This feature is now checked in (v0.55) and live on my served copy. I'll close the issue after a while, unless there are follow-ups needing tweaks.

**Comment by viresh-ratnakar** [comment]
Closing, please reopen if there are any follow-ups.
