### ISSUE TITLE
How does 'automatic clue numbering' work?

### ISSUE THREAD

**Issue by MaheshVelankar** [viresh-ratnakar/exolve#92]
This is not an issue
I am trying to understand the clue numbering part. 
The 'Read me' says 'clue numbers can be automatically inferred'  .... Do you mean that setter can only give the clues in a list and the software will give the proper cell numbers to corresponding clue? How to do that?.........
Or the setter 'has to know' the cell number (that the software will give to the word start) and 'has to specify' that cell number to the clue for that word?.... If that is the case then what is the use of automatically giving the cell numbers in the grid?... because setter will have to know them anyway (to specify them in the clues)

Am I missing anything here? (personally I do not have problems in specifying cell numbers myself (and the clue numbers)... but "automatically inferring" of clue numbers got me interested...........Please see if you can enlighten me (in your free time.)

**Comment by viresh-ratnakar** [comment]
Yeah, all I meant was that the clue numbering *within the grid* is inferred. I've clarified that now by updating the README.

It would be indeed possible to not even require clue numbers to be specified in the list of clues (and that would indeed be truly "automatic inferring of clue numbers"), but I think it's not needed as a feature and may even lead to unintentional errors while setting.

Will close this Issue shortly, unless there are follow-ups. Thanks!

**Comment by viresh-ratnakar** [comment]
Closing; please reopen if there are any follow-ups, thanks.
