### ISSUE TITLE
.xlv-only-print doesn't work (mentioned in README.md)

### ISSUE THREAD

**Issue by DKMiller71** [viresh-ratnakar/exolve#97]
README.md says the class `.xlv-only-print` should cause the element to only appear in print not on screen, however it doesn't seem to work (appears both on screen and in print).  I can't find the class described in the code anywhere.  

Its counterpart `.xlv-dont-print` seems to work fine.

Workaround:
Add the following to your stylesheet:
```
@media screen {
	.xlv-only-print { visibility: hidden;  }
}
```

**Comment by viresh-ratnakar** [comment]
Hmm.. the support for this was added in Exolve v1.56.3:

https://github.com/viresh-ratnakar/exolve/commit/c43aedfd32a3bbbe899527a36e4a832c66ba14d6

The following lines (similar to what you have above) should be already there in exolve-m.css:
```
@media not print {
  .xlv-only-print {
    display: none;
  }
}
```

**Comment by DKMiller71** [comment]
Apparently I wasn't seeing the latest ... did a re-pull and got the updates... sorry about the mix-up.

**Comment by DKMiller71** [comment]
local update error

**Comment by viresh-ratnakar** [comment]
No worries at all!
